
# Use "host.docker.internal" instead of "127.0.0.1" or "localhost"

server {
  listen       80;
  listen  [::]:80;
  server_name  api.keyman.com.localhost api.keyman.com;
  location / {
    proxy_pass http://host.docker.internal:8058;
  }
}

server {
  listen       80;
  listen  [::]:80;
  server_name  help.keyman.com.localhost help.keyman.com;
  location / {
    proxy_pass http://host.docker.internal:8055;
  }
}

server {
  listen       80;
  listen  [::]:80;
  server_name  keyman.com.localhost keyman.com;
  location / {
    proxy_pass http://host.docker.internal:8053;
  }
}

server {
  listen       80;
  listen  [::]:80;
  server_name  web.keyman.com.localhost keymanweb.com.localhost web.keyman.com keymanweb.com;
  location / {
    proxy_pass http://host.docker.internal:8057;
  }
}

server {
  listen       80;
  listen  [::]:80;
  server_name  s.keyman.com.localhost s.keyman.com;
  location / {
    proxy_pass http://host.docker.internal:8054;
  }
}

# note that in production, this port is not used for status.keyman.com
server {
  listen       80;
  listen  [::]:80;
  server_name  status.keyman.com.localhost status.keyman.com;
  location / {
    proxy_pass http://host.docker.internal:8061;
  }
}

# in development mode, backend is separate to frontend for status.keyman.com
# note that in production, 8060 is the backend and frontend!
server {
  listen       80;
  listen  [::]:80;
  server_name  status-backend.keyman.com.localhost status-backend.keyman.com;
  location / {
    proxy_pass http://host.docker.internal:8060;
  }
}
